# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pinout.xdc

# Block Designs: bd/cpu_system/cpu_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_system || ORIG_REF_NAME==cpu_system} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_microblaze_0_0/cpu_system_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_system_microblaze_0_0 || ORIG_REF_NAME==cpu_system_microblaze_0_0} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_dlmb_v10_0/cpu_system_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_system_dlmb_v10_0 || ORIG_REF_NAME==cpu_system_dlmb_v10_0} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_ilmb_v10_0/cpu_system_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_system_ilmb_v10_0 || ORIG_REF_NAME==cpu_system_ilmb_v10_0} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_dlmb_bram_if_cntlr_0/cpu_system_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_system_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==cpu_system_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_ilmb_bram_if_cntlr_0/cpu_system_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_system_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==cpu_system_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_lmb_bram_0/cpu_system_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_system_lmb_bram_0 || ORIG_REF_NAME==cpu_system_lmb_bram_0} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_microblaze_0_axi_periph_0/cpu_system_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_system_microblaze_0_axi_periph_0 || ORIG_REF_NAME==cpu_system_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_microblaze_0_axi_intc_0/cpu_system_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_system_microblaze_0_axi_intc_0 || ORIG_REF_NAME==cpu_system_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_microblaze_0_xlconcat_0/cpu_system_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_system_microblaze_0_xlconcat_0 || ORIG_REF_NAME==cpu_system_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_mdm_1_0/cpu_system_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_system_mdm_1_0 || ORIG_REF_NAME==cpu_system_mdm_1_0} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_clk_wiz_1_0/cpu_system_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_system_clk_wiz_1_0 || ORIG_REF_NAME==cpu_system_clk_wiz_1_0} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_rst_clk_wiz_1_100M_0/cpu_system_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_system_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==cpu_system_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_axi_gpio_0_0/cpu_system_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_system_axi_gpio_0_0 || ORIG_REF_NAME==cpu_system_axi_gpio_0_0} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_axi_gpio_1_0/cpu_system_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_system_axi_gpio_1_0 || ORIG_REF_NAME==cpu_system_axi_gpio_1_0} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_axi_timer_0_0/cpu_system_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_system_axi_timer_0_0 || ORIG_REF_NAME==cpu_system_axi_timer_0_0} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_axi_uartlite_0_0/cpu_system_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_system_axi_uartlite_0_0 || ORIG_REF_NAME==cpu_system_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/cpu_system/ip/cpu_system_xbar_0/cpu_system_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_system_xbar_0 || ORIG_REF_NAME==cpu_system_xbar_0} -quiet] -quiet

# XDC: e:/Egyetem/fpga_alapu_rendszerek/mb_system2/mb_system2.gen/sources_1/bd/cpu_system/cpu_system_ooc.xdc
