
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.2.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_GPIO_LED_DISP_DEVICE_ID,
		XPAR_GPIO_LED_DISP_BASEADDR,
		XPAR_GPIO_LED_DISP_INTERRUPT_PRESENT,
		XPAR_GPIO_LED_DISP_IS_DUAL
	},
	{
		XPAR_GPIO_SW_BTN_DEVICE_ID,
		XPAR_GPIO_SW_BTN_BASEADDR,
		XPAR_GPIO_SW_BTN_INTERRUPT_PRESENT,
		XPAR_GPIO_SW_BTN_IS_DUAL
	}
};


