set_property IOSTANDARD LVCMOS33 [get_ports clk100M_in]
set_property IOSTANDARD LVCMOS33 [get_ports rst_in]
set_property IOSTANDARD LVCMOS33 [get_ports UART_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports UART_txd]
set_property PACKAGE_PIN L23 [get_ports rst_in]
set_property PACKAGE_PIN D23 [get_ports clk100M_in]
set_property PACKAGE_PIN M21 [get_ports UART_txd]
set_property PACKAGE_PIN N21 [get_ports UART_rxd]
set_property LOC BUFGCTRL_X0Y2 [get_cells clk100M_bufg]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
