set_property PACKAGE_PIN D23 [get_ports {clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {clk}]

set_property PACKAGE_PIN L23 [get_ports {rst}]
set_property IOSTANDARD LVCMOS33 [get_ports {rst}]

set_property PACKAGE_PIN F10 [get_ports {digsel[0]}]
set_property PACKAGE_PIN D11 [get_ports {digsel[1]}]
set_property PACKAGE_PIN D10 [get_ports {digsel[2]}]
set_property PACKAGE_PIN B10 [get_ports {digsel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digsel*}]

set_property PACKAGE_PIN D8 [get_ports {seg[0]}]
set_property PACKAGE_PIN E10 [get_ports {seg[1]}]
set_property PACKAGE_PIN B9 [get_ports {seg[2]}]
set_property PACKAGE_PIN D9 [get_ports {seg[3]}]
set_property PACKAGE_PIN E13 [get_ports {seg[4]}]
set_property PACKAGE_PIN G11 [get_ports {seg[5]}]
set_property PACKAGE_PIN C9 [get_ports {seg[6]}]
set_property PACKAGE_PIN G10 [get_ports {seg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg*}]
